// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORION.WebAPI.DbContexts;

#nullable disable

namespace ORION.WebAPI.Migrations
{
    [DbContext(typeof(OrionContext))]
    partial class OrionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ORION.WebAPI.Entities.EmployeeDepartmentHistory", b =>
                {
                    b.Property<int>("BusinessEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BusinessEntityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessEntityId"));

                    b.Property<short>("DepartmentId")
                        .HasColumnType("smallint")
                        .HasColumnName("DepartmentID");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<byte>("ShiftId")
                        .HasColumnType("tinyint")
                        .HasColumnName("ShiftID");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("BusinessEntityId");

                    b.HasIndex(new[] { "DepartmentId" }, "IX_EmployeeDepartmentHistory_DepartmentID");

                    b.HasIndex(new[] { "ShiftId" }, "IX_EmployeeDepartmentHistory_ShiftID");

                    b.ToTable("EmployeeDepartmentHistory", "HumanResources");
                });

            modelBuilder.Entity("ORION.WebAPI.Entities.Shift", b =>
                {
                    b.Property<byte>("ShiftId")
                        .HasColumnType("tinyint")
                        .HasColumnName("ShiftID");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("ShiftId");

                    b.HasIndex(new[] { "Name" }, "AK_Shift_Name")
                        .IsUnique();

                    b.HasIndex(new[] { "StartTime", "EndTime" }, "AK_Shift_StartTime_EndTime")
                        .IsUnique();

                    b.ToTable("Shift", "HumanResources");
                });
#pragma warning restore 612, 618
        }
    }
}
